spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/api/v1/users/**
        filters:
          - StripPrefix=2
      - id: posts-service
        uri: lb://POSTS-SERVICE
        predicates:
          - Path=/api/v1/posts/**
        filters:
          - StripPrefix=2

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8762/eureka/


